// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADPoBUeLXGYgmbfUx1QbvQLKB8TpYCLTQ',
    appId: '1:615883665564:web:a0022be384158d42647d59',
    messagingSenderId: '615883665564',
    projectId: 'finalproject-7399f',
    authDomain: 'finalproject-7399f.firebaseapp.com',
    storageBucket: 'finalproject-7399f.firebasestorage.app',
    measurementId: 'G-SDNEXPX5N7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpB8SlbK3Q9VGY9_4IFMtCGM4x8c3yaew',
    appId: '1:615883665564:android:e796f8cee0352400647d59',
    messagingSenderId: '615883665564',
    projectId: 'finalproject-7399f',
    storageBucket: 'finalproject-7399f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIXMjt7mujUhecaX4CW5Yo9dl15--R2fg',
    appId: '1:615883665564:ios:5ecebba1a731ebcc647d59',
    messagingSenderId: '615883665564',
    projectId: 'finalproject-7399f',
    storageBucket: 'finalproject-7399f.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIXMjt7mujUhecaX4CW5Yo9dl15--R2fg',
    appId: '1:615883665564:ios:5ecebba1a731ebcc647d59',
    messagingSenderId: '615883665564',
    projectId: 'finalproject-7399f',
    storageBucket: 'finalproject-7399f.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADPoBUeLXGYgmbfUx1QbvQLKB8TpYCLTQ',
    appId: '1:615883665564:web:7f5aa8c4f4f3c498647d59',
    messagingSenderId: '615883665564',
    projectId: 'finalproject-7399f',
    authDomain: 'finalproject-7399f.firebaseapp.com',
    storageBucket: 'finalproject-7399f.firebasestorage.app',
    measurementId: 'G-H2Y6XC4H7Q',
  );

}